package main

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/conduitio/conduit/pkg/registry/index"
	"github.com/conduitio/conduit/pkg/registry/trust"
	"github.com/sigstore/sigstore-go/pkg/testing/ca"
)

// TestGenerateSignedFixture generates a root-signed index fixture plus its
// TrustAnchors file from the committed TEMPLATE payload
// (test/fixtures/sample-index.json), so the site's build-pipeline tests can
// drive the REAL verifier CLI offline (vitest shells out to this test with
// FIXTURE_OUT_DIR set, then points --index / --anchors-file at the
// generated files). The fixture is signed with a freshly generated test key
// and stamped with `now`, so it is never stale at generation time and never
// touches production keys or the network.
//
// The committed template's own root signature is FAKE (a synthetic keyId and
// signature bytes — it exists only so the pre-S2 TS structural stub had an
// envelope to check). Nothing may ever treat it as trusted; that is asserted
// by TestCommittedTemplateIsNotTrusted below.
const fixtureOutDirEnv = "FIXTURE_OUT_DIR"

func TestGenerateSignedFixture(t *testing.T) {
	outDir := os.Getenv(fixtureOutDirEnv)
	if outDir == "" {
		t.Skip("FIXTURE_OUT_DIR not set — nothing to write; set it to generate the site's offline fixture (scripts/tests shell out to this)")
	}

	// Load the committed template and keep only its payload, the source of
	// the site's render-model data (schemaVersion 1, 2 connectors).
	templatePath := filepath.Join("..", "..", "test", "fixtures", "sample-index.json")
	templateRaw, err := os.ReadFile(templatePath)
	if err != nil {
		t.Fatalf("reading template fixture: %v", err)
	}
	var envelope map[string]json.RawMessage
	if err := json.Unmarshal(templateRaw, &envelope); err != nil {
		t.Fatalf("parsing template fixture: %v", err)
	}
	var payload map[string]any
	if err := json.Unmarshal(envelope["payload"], &payload); err != nil {
		t.Fatalf("parsing template payload: %v", err)
	}

	// Stamp the current time so the fixture passes the CLI's own 7-day
	// staleness window against the wall clock.
	indexObj, ok := payload["index"].(map[string]any)
	if !ok {
		t.Fatalf("template payload has no index object")
	}
	indexObj["timestamp"] = time.Now().UTC().Format(time.RFC3339)

	// WS4 S3: rewrite every artifact's sha256 + bundle references onto REAL
	// sigstore material generated by a VirtualSigstore CA, so the signed
	// fixture carries verifiable signature+provenance bundles and the
	// integration suite can drive the real --artifacts pass offline via
	// --trust-root-file. The rewrite happens BEFORE signing, so the signed
	// index declares exactly what the bundles prove.
	ss, _ := newVirtualCA(t)
	rewritePayloadArtifacts(t, payload, ss, outDir)

	stampedPayload, err := json.Marshal(payload)
	if err != nil {
		t.Fatalf("re-marshaling stamped payload: %v", err)
	}

	// Sign exactly the way the index-sign tool does (signPayload: JCS
	// canonicalize + index.KeyID + ed25519), root role only — the site's
	// build always runs with --require-root.
	pub, priv := mustGenerateKey(t)
	signedEnvelope := signPayload(t, stampedPayload, "root", priv)

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		t.Fatalf("creating fixture dir: %v", err)
	}
	if err := os.WriteFile(filepath.Join(outDir, "signed-index.json"), signedEnvelope, 0o644); err != nil {
		t.Fatalf("writing signed fixture: %v", err)
	}

	keyID, err := index.KeyID(pub)
	if err != nil {
		t.Fatalf("deriving keyId: %v", err)
	}
	anchors := map[string]any{
		"roots":     map[string]any{keyID: pub},
		"freshness": map[string]any{},
	}
	anchorsJSON, err := json.Marshal(anchors)
	if err != nil {
		t.Fatalf("marshaling anchors file: %v", err)
	}
	if err := os.WriteFile(filepath.Join(outDir, "anchors.json"), anchorsJSON, 0o644); err != nil {
		t.Fatalf("writing anchors file: %v", err)
	}
	trustRootJSON := virtualTrustRootJSON(t, ss)
	if err := os.WriteFile(filepath.Join(outDir, "trust-root.json"), trustRootJSON, 0o644); err != nil {
		t.Fatalf("writing trust root file: %v", err)
	}

	// Round-trip proof: the generated fixture must verify through run() with
	// the generated anchors, byte-for-byte, with --require-root — the exact
	// invocation the site build makes. The artifacts pass runs against the
	// SAME signed payload, and every well-signed version must come out pass
	// while the provenance-less 0.14.2 honesty case must come out
	// not_attempted("no provenance in index").
	statePath, outPath := tempPaths(t)
	artifactsPath := filepath.Join(outDir, "artifacts.json")
	if err := run(context.Background(), options{
		indexURL:     filepath.Join(outDir, "signed-index.json"),
		outPath:      outPath,
		statePath:    statePath,
		anchors:      testAnchors(pub),
		requireRoot:  true,
		artifactsOut: artifactsPath,
		trustRoot:    virtualTrustRootFor(t, ss),
		now:          time.Now,
	}); err != nil {
		t.Fatalf("generated fixture does not verify through the real pipeline: %v", err)
	}
	written, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("reading verified out file: %v", err)
	}
	if string(written) != string(signedEnvelope) {
		t.Fatalf("out bytes do not match the signed fixture")
	}
	assertFixtureVerdicts(t, artifactsPath)
}

// rewritePayloadArtifacts replaces every artifact's sha256 and bundle refs
// with locally generated sigstore material: the sha256 becomes the digest of
// a deterministic fixture artifact payload, signature.bundleURL and
// slsaProvenance.bundleURL (artifact-level, else version-level) become
// absolute paths to generated bundles, and rekorLogIndex is dropped (no
// longer meaningful). A version-level provenance bundle carries one subject
// per artifact digest (CheckProvenanceBinding matches ANY subject), so the
// single shared bundle binds every artifact. Versions declaring no
// provenance keep their refs nil — the not_attempted honesty case.
func rewritePayloadArtifacts(t *testing.T, payload map[string]any, ss *ca.VirtualSigstore, outDir string) {
	t.Helper()
	connectors, ok := payload["connectors"].([]any)
	if !ok {
		t.Fatalf("payload has no connectors list")
	}
	for _, cAny := range connectors {
		conn := cAny.(map[string]any)
		pattern, _ := conn["publisher"].(map[string]any)["expectedIdentityPattern"].(string)
		versions, _ := conn["versions"].([]any)
		for _, vAny := range versions {
			v := vAny.(map[string]any)
			version, _ := v["version"].(string)
			identity := concreteIdentityFromPattern(pattern, version)
			artifacts, _ := v["artifacts"].([]any)
			if len(artifacts) == 0 {
				continue
			}
			// First pass: deterministic artifact bytes + signature bundles,
			// collecting the declared digests the version-level provenance
			// must bind to.
			digests := make([]string, 0, len(artifacts))
			for _, aAny := range artifacts {
				a := aAny.(map[string]any)
				osName, _ := a["os"].(string)
				arch, _ := a["arch"].(string)
				artifactBytes := []byte(fmt.Sprintf("fixture-artifact-%s-%s-%s-%s", conn["name"], version, osName, arch))
				a["sha256"] = fmt.Sprintf("%x", sha256Sum(artifactBytes))
				a["size"] = int64(len(artifactBytes))
				digests = append(digests, a["sha256"].(string))
				sigPath := filepath.Join(outDir, fmt.Sprintf("sig-%s-%s-%s-%s.json", conn["name"], version, osName, arch))
				if err := os.WriteFile(sigPath, signatureBundleJSON(t, ss, identity, testIssuer, artifactBytes), 0o644); err != nil {
					t.Fatalf("writing signature bundle: %v", err)
				}
				a["signature"].(map[string]any)["bundleURL"] = sigPath
				delete(a["signature"].(map[string]any), "rekorLogIndex")
			}
			// Second pass: provenance refs. Artifact-level overrides the
			// version-level ref; a version with neither keeps none (the
			// not_attempted honesty case).
			provRef, hasVersionProv := v["slsaProvenance"].(map[string]any)
			var versionProvPath string
			if hasVersionProv {
				versionProvPath = generateProvisionBundle(t, ss, outDir, "version-"+version, digests)
				provRef["bundleURL"] = versionProvPath
			}
			for i, aAny := range artifacts {
				a := aAny.(map[string]any)
				if provAny, hasProv := a["slsaProvenance"].(map[string]any); hasProv {
					provAny["bundleURL"] = generateProvisionBundle(t, ss, outDir, fmt.Sprintf("art-%s-%d", version, i), []string{digests[i]})
				} else if hasVersionProv {
					a["slsaProvenance"] = map[string]any{
						"bundleURL":     versionProvPath,
						"predicateType": "https://slsa.dev/provenance/v1",
					}
				}
			}
		}
	}
}

// generateProvisionBundle writes a provenance bundle signed by the SLSA
// builder identity, its statement subject-bound to every digest in digests
// (the shape slsa-github-generator emits for a multi-artifact release), and
// returns its path.
func generateProvisionBundle(t *testing.T, ss *ca.VirtualSigstore, outDir, name string, digests []string) string {
	t.Helper()
	path := filepath.Join(outDir, "prov-"+name+".json")
	if err := os.WriteFile(path, provenanceBundleJSON(t, ss, trust.ExpectedBuilderID, testIssuer, slsaStatementJSON(digests...)), 0o644); err != nil {
		t.Fatalf("writing provenance bundle: %v", err)
	}
	return path
}

// concreteIdentityFromPattern builds a signing identity the connector's
// pinned pattern accepts: the literal prefix with escaped dots unescaped,
// and the trailing version regex substituted with the concrete version.
func concreteIdentityFromPattern(pattern, version string) string {
	// The version regex is substituted BEFORE unescaping the dots — the
	// pattern's `\.` escapes would otherwise destroy the match target.
	s := strings.ReplaceAll(pattern, `[0-9]+\.[0-9]+\.[0-9]+`, version)
	s = strings.ReplaceAll(s, `\.`, ".")
	return strings.TrimSuffix(strings.TrimPrefix(s, "^"), "$")
}

// assertFixtureVerdicts checks the generated artifacts report: every version
// with provenance must be pass, the provenance-less 0.14.2 must be
// not_attempted with the no-provenance reason, and fail/not_attempted must
// carry reasons.
func assertFixtureVerdicts(t *testing.T, artifactsPath string) {
	t.Helper()
	raw, err := os.ReadFile(artifactsPath)
	if err != nil {
		t.Fatalf("reading artifacts report: %v", err)
	}
	var report artifactsReport
	if err := json.Unmarshal(raw, &report); err != nil {
		t.Fatalf("parsing artifacts report: %v", err)
	}
	if report.SchemaVersion != 1 {
		t.Fatalf("unexpected report schemaVersion %d", report.SchemaVersion)
	}
	versionVerdicts := map[string]artifactVerdict{}
	versionReasons := map[string]string{}
	for _, c := range report.Connectors {
		for _, v := range c.Versions {
			versionVerdicts[v.Version] = v.Verdict
			versionReasons[v.Version] = v.Reason
		}
	}
	for version, want := range map[string]artifactVerdict{
		"0.14.0": verdictPass,
		"0.14.1": verdictPass,
		"0.3.0":  verdictPass,
		"0.14.2": verdictNotAttempted,
	} {
		if versionVerdicts[version] != want {
			t.Fatalf("version %s: expected verdict %q, got %q (%q)", version, want, versionVerdicts[version], versionReasons[version])
		}
	}
	if versionReasons["0.14.2"] != reasonNoProvenance {
		t.Fatalf("0.14.2: expected reason %q, got %q", reasonNoProvenance, versionReasons["0.14.2"])
	}
}

// TestCommittedTemplateIsNotTrusted is the honesty guard for the fixture
// strategy. The committed template's root signature is synthetic (a made-up
// keyId and signature bytes), so the real verifier must REFUSE it — anchored
// against the REAL production anchors (productionAnchors(), the same set the
// site build verifies with), not a test key: the premise is that the template
// is trusted by NO key in the production trust core. If this test starts
// passing, someone signed the template with a production root key and the
// "fake signature" premise in this file's doc comment is stale.
func TestCommittedTemplateIsNotTrusted(t *testing.T) {
	anchors, err := productionAnchors()
	if err != nil {
		t.Fatalf("production anchors unavailable: %v", err)
	}
	_, outPath := tempPaths(t)
	err = run(context.Background(), options{
		indexURL:    filepath.Join("..", "..", "test", "fixtures", "sample-index.json"),
		outPath:     outPath,
		statePath:   filepath.Join(t.TempDir(), "state.json"),
		anchors:     anchors,
		requireRoot: true,
		now:         time.Now,
	})
	if err == nil {
		t.Fatalf("committed template verified — the fake root signature is being trusted, fixture premise broken")
	}
	if _, statErr := os.Stat(outPath); statErr == nil {
		t.Fatalf("rejected index still wrote an out file — fail-closed violated")
	}
}
